name: Daily modal queries
on:
  schedule:
    - cron: "0 6 * * *"  # daily at 06:00 UTC
  workflow_dispatch: {}

jobs:
  run-queries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true
      - name: Ensure Python available for uv
        run: uv python install
      - name: Install dependencies with uv
        env:
          UV_SYSTEM_PYTHON: 1
        run: uv pip install requests langchain langchain-openai
      - name: Run queries
        env:
          MODAL_ENDPOINT_URL: ${{ secrets.MODAL_ENDPOINT_URL }}
          ENDPOINT_AUTH_TOKEN: ${{ secrets.ENDPOINT_AUTH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          uv run python scripts/run_queries.py
